#include <stdio.h>
//#include "trainermenu.h"
//#include "GBAATMres.h"
//#include "resource.h"
//#include "mystructs.h"
//#include "strfuncs.cpp"
//#include "genfuncs.cpp"
//#include "romfuncs.cpp"
//#include "valuetestfuncs.cpp"
